repositories:
  - name: argo
    url: https://argoproj.github.io/argo-helm

environments:
  dev:
  prod:

releases:
  - name: argo-rollouts
    namespace: argo-rollouts
    atomic: true
    createNamespace: true
    chart: argo/argo-rollouts
    version: "2.22.3"
    values:
      - environment/{{ .Environment.Name }}/argo-rollouts-values.yaml
